 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2025-09-22 10:17:28,652 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2025-09-22 10:17:28,653 - werkzeug - INFO -  * Running on http://109.71.242.95:5000/ (Press CTRL+C to quit)
2025-09-22 10:17:28,664 - werkzeug - INFO -  * Restarting with watchdog (inotify)
2025-09-22 10:17:28,965 - werkzeug - WARNING -  * Debugger is active!
2025-09-22 10:17:28,969 - werkzeug - INFO -  * Debugger PIN: 946-581-459
2025-09-22 10:17:40,008 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:40] "GET / HTTP/1.1" 302 -
2025-09-22 10:17:40,052 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:40] "GET /dashboard HTTP/1.1" 302 -
2025-09-22 10:17:40,112 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:40] "GET /login?next=%2Fdashboard HTTP/1.1" 200 -
2025-09-22 10:17:40,746 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:40] "GET /favicon.ico HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/root/StreamOfflineV3/app.py", line 52, in page_not_found
    return render_template('404.html'), 404
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2025-09-22 10:17:51,215 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:51] "POST /login?next=%2Fdashboard HTTP/1.1" 302 -
2025-09-22 10:17:51,259 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:51] "GET /dashboard HTTP/1.1" 302 -
2025-09-22 10:17:51,305 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:51] "GET /login?next=%2Fdashboard HTTP/1.1" 200 -
2025-09-22 10:17:51,404 - werkzeug - INFO - 146.158.104.155 - - [22/Sep/2025 10:17:51] "GET /favicon.ico HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/root/StreamOfflineV3/app.py", line 52, in page_not_found
    return render_template('404.html'), 404
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/root/StreamOfflineV3/venv/lib/python3.12/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
